version: "3.9"

services:

  mongo:
    image: mongo:5.0
    container_name: 'mongo_db'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=ftp_data 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017
    networks:
      - app-network


  redis:
    image: redis:6.2-alpine
    command: redis-server 
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network


networks:
  app-network:
    driver: bridge